# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/.'
      - '/tools/code-style'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    allow:
      - dependency-type: 'all'
    versioning-strategy: 'auto'
    labels: [ 'dependencies' ]
    commit-message:
      prefix: 'chore'  ## prefix maximum string length of 15
      include: 'scope'
    open-pull-requests-limit: 999
    ignore:
      - dependency-name: "@types/node"
        # version is like `ts.X.Y` -- need to maintain manually
    groups:
      cyclonedx:
        patterns:
          - '@cyclonedx/*'
      spdx:
        patterns:
          - 'spdx-*'
          - '@types/spdx-*'
      ajv:
        patterns:
          - 'ajv'
          - 'ajv-*'
      typescript:
        patterns:
          - 'typescript'
          - '@types/*'
          - 'typedoc'
          - 'typedoc-*'
          - '@microsoft/tsdoc'
          - '@microsoft/tsdoc-*'
          - 'ts-loader'
          - 'tslib'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - '*-eslint'
          - 'eslint-*'
          - '@types/eslint'
          - '@types/eslint-*'
          - '@types/*-eslint'
          - '@eslint-community/*'
          - '@typescript-eslint/*'
      webpack:
        patterns:
          - 'webpack'
          - 'webpack-*'
          - '@webpack-cli/*'
          - '@webassemblyjs/*'
          - 'browserslist'
          - 'caniuse-*'
          - 'ts-loader'
          - '*-webpack-plugin'
      jest:
        patterns:
          - 'jest'
          - '@jest/*'
          - 'jest-*'
          - 'babel-jest'
          - '@types/jest'
          - '@types/jest*'
      babel:
        patterns:
          - 'babel'
          - '@babel/*'
          - 'babel-*'
          - '@types/babel*'
      angular:
        patterns:
          - '@angular/*'
          - '@angular-*/*'
      karma:
        patterns:
          - 'karma'
          - 'karma-*'
      jasmine:
        patterns:
          - 'jasmine'
          - 'jasmine-*'
          - '@types/jasmine'
          - '@types/jasmine*'
      react:
        patterns:
          - 'react'
          - 'react-*'
      postcss:
        patterns:
          - 'postcss'
          - 'postcss-*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    labels: [ 'dependencies' ]
    commit-message:
      prefix: 'chore'   ## prefix maximum string length of 15
      include: 'scope'
    open-pull-requests-limit: 999
