blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/CycloneDX/cyclonedx-webpack-plugin/discussions
    about: Please ask and answer questions here.
  - name: Community slack support channel
    url: https://cyclonedx.slack.com/archives/C02E5182DM1
    about: Community slack channel.
  - name: Community slack invite
    url: https://cyclonedx.org/slack/invite
    about: Community slack invite.
